version: 2
jobs:
  build:
    working_directory: ~/ProductCatalog
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions  
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run UnitTest
          command: ./gradlew test
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
      working_directory: /tmp
        steps:
            - run:
              name: Creating Dummy Artifacts
              command: |
                echo "my artifact file" > /tmp/art-1;
                mkdir /tmp/artifacts;
                echo "my artifact files in a dir" > /tmp/artifacts/art-2;
                - store_artifacts:
                    path: /tmp/art-1
                    destination: artifact-file
                - store_artifacts:
                    path: /tmp/artifacts